workflows:
  hello-world:
    name: Hello world workflow
    instance_type: mac_pro
    max_build_duration: 60
    environment:
       groups:             # Define your environment variables groups here
         - keystore_credentials
         - app_store_credentials
       vars:
         GOOGLE_PLAY_TRACK: "beta"
       flutter: stable   # Define the channel name, version (e.g. v1.13.4), or fvm for Flutter Version Management
       xcode: latest     # Define latest, edge or version (e.g. 11.2)
       cocoapods: 1.9.1  # Define default or version
       node: 12.14.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
       npm: 6.13.7       # Define default, latest, next, lts or version
       ndk: r21d         # Define default or revision (e.g. r19c)
       java: 1.8         # Define default, or platform version (e.g. 11)
       ruby: 2.7.2
    cache:
      cache_paths:
        - $HOME/ .gradle/cache
        - $FLUTTER_ROOT/ .pub-cache
        - $HOME/Library/cache/cocoapods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:                       # List the events that trigger builds
        - push
        - pull_request
        - tag
       branch_patterns:              # Include or exclude watched branches
         - pattern: '*'
           include: true
           source: true
    scripts:
      - name: Get Flutter packages
        script: flutter package pub get
      - name: Build apk
        script: flutter build apk --release
      - name: Build for iOS
        script: flutter build ios
    artifacts:
      - build/**/outputs/apk/**/*.apk                   # relative path for a project in root directory
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - manimv1268@gmail.com           